version: '2'
services:
    repository-app:
        image: repository
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://repository-mysql:3306/repository?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://repository-elasticsearch:9200
        ports:
            - 8080:8080
    repository-mysql:
        extends:
            file: mysql.yml
            service: repository-mysql
    repository-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: repository-elasticsearch
